### ISSUE TITLE
Statement coverage incorrect

### ISSUE THREAD

**Issue by valbg** [danielpalme/ReportGenerator#11]
Hi,

I just updated my setup from v1.7.3 to v2.1.4 and although it now looks much nicer I noticed huge bump in the coverable/covered lines and realised it now counts things that it shouldn't be / previously wasn't. 

Please see screenshots attached:

Previous correct behaviour:
![old](https://cloud.githubusercontent.com/assets/5405847/6800413/2550783e-d216-11e4-94c7-ea717986cf45.PNG)

The current (suspicious) behaviour:
![new](https://cloud.githubusercontent.com/assets/5405847/6800453/7ec959da-d216-11e4-8405-7abee7959f11.PNG)

**Comment by danielpalme** [comment]
You are right, the behavior changed in v.2.0.
See this discussion: http://reportgenerator.codeplex.com/discussions/549378.

From a "statement coverage" point of view, the old behavior was more "correct".
From a "line coverage" point of view, the new behavior is more "correct".

Since ReportGenerator is more a line coverage tool, I decided to change the behavior.
There is no wrong or right here, it's just a matter of taste.

**Comment by valbg** [comment]
So no chance of this being supported (optionally) in a later version, then?

**Comment by danielpalme** [comment]
I don't think there will be an option for that. The new behavior is different but not wrong.
The new behavior is more consistent with the other output of ReportGenerator.

You will get used to it :-)

In general I try to reduce options as much as possible.
More options make the code more complex and users should not have to make too many decisions.
