### ISSUE TITLE
Question - ReportGenerator and OpenCoverToCoberturaConverter

### ISSUE THREAD

**Issue by ivancitin** [danielpalme/ReportGenerator#122]
Hello Daniel Palme,

First, thank you for this usefull tools. I'm observing that the conversion using ReportGenerator and OpenCoverToCoberturaConverter based on the same OpenCover report, generate different coverage.

ReportGenerator generates a higher coverage than OpenCoverToCoberturaConverter, is this something you have observed, do you have an idea what could be possible causing it, and how can I get around it.

With the new version, I can use ReportGenerator to get the HTML report based on the cobertura report generated by OpenCoverToCoberturaConverter, but i was expecting same results if i use the same opencover report as the input for both tools.

Thanks,
Ivan

**Comment by danielpalme** [comment]
Hi Ivan,
in theory you are right, in practice things are more complicated.
_OpenCoverToCoberturaConverter_ converts the _OpenCover_ file to a _Cobertura_ file.
The conversion of _OpenCoverToCoberturaConverter_ is not 100% "perfect". I don't remember the details, since I wrote the conversion 4 years ago.
To analyze this we need:
- Source code of your application
- The OpenCover file
- The Cobertura file

**Comment by danielpalme** [comment]
Closing this for now. Please reopen if you can provide some more information
