### ISSUE TITLE
Including / excluding getters, setters and lamda expressions via command line argument

### ISSUE THREAD

**Issue by talberti** [danielpalme/ReportGenerator#162]
I would like the ability to allow getters, setters and lamda expressions to be counted in the blocks covered or line coverage.  The reason for this is because by default visual studio code coverage reports these as covered.  This should be controlled via a command line argument rather then hard coding it into the parser.

**Comment by danielpalme** [comment]
I understand what you are trying to archive.

I have always tried to keep the number of possible command line parameters as small as possible and only added new parameters, when I was convinced that they are easy to understand and useful for the majority of the users.
Otherwise ReportGenerator would end up with (too) many parameters that no one understands.

I'm not sure if this parameter is really useful for the majority of the users.

**Comment by talberti** [comment]
I completely understand, and I think less is more is a good thing. I'm just trying to figure out a solution without the need to fork the entire project.

**Comment by danielpalme** [comment]
Closing this for now.
