### ISSUE TITLE
Strange styles in AzureDevOps coverage reports

### ISSUE THREAD

**Issue by gfletcherMerc** [danielpalme/ReportGenerator#176]
We're using ReportGenerator 4.0.3 from NuGet integrated into an AzureDevOps pipeline with Cobertura input and a report type of HTMLInline_AzurePipeline.

If we look at the ReportGenerator output folder we see nice (consistent with AzureDevOps) fonts:
![image](https://user-images.githubusercontent.com/41027543/48415304-ee80a200-e744-11e8-97c9-720aaf96b2b8.png)

But those fonts look different when viewed in AzureDevOps (after a publish coverage results step):
![image](https://user-images.githubusercontent.com/41027543/48415361-196af600-e745-11e8-8e3d-39fd2defdd6b.png)

Is this hinting at a CSS issue?

**Comment by danielpalme** [comment]
@knom is currenty investigating this issue (see #174).
Probably AzureDevOps is stripping off the CSS rules regarding the fonts.

**Comment by gfletcherMerc** [comment]
Thanks @danielpalme, if you or @knom want me to test a NuGet debug/dev version please just @ me

**Comment by gfletcherMerc** [comment]
I see that font-family in the CSS in both the ReportGenerator output folder and in the coverage report in AzureDevOps.

The images above were generated today, but not using your AzureDevOps task from the market place. I believe that task uses .NET core 2.0 and we don't have that on the self-hosted build agents we're using. We have our own lump of Powershell which gets the latest (4.0.3 currently) ReportGenerator package from NuGet & we run that (with HtmlInline_AzurePipeline report type selected)

**Comment by knom** [comment]
I can reproduce, but don't really know how to fix it right now..

@gfletcherMerc do you mind attaching the HTML output (of the coverage report)?

**Comment by danielpalme** [comment]
I would guess that if you download the coverage report, you get the complete HTML files.
But if you view the files in AzureDevOps, the CSS is modified on the fly.

**Comment by knom** [comment]
OK.. Azure DevOps seems to modify the files for security reasons.
I'm talking to the team and will update..

**Comment by danielpalme** [comment]
I just created my own Azure Pipeline and can confirm that the font family is removed from the HTML.

But I'm currently working at a workaround. Looks promising so far. Hopefully I can provide a new release tomorrow.

**Comment by danielpalme** [comment]
I was able to fix the problem by trial and error.
By using
`font-family: 'Segoe UI', '-apple-system', BlinkMacSystemFont, Roboto, 'Helvetica Neue', Helvetica, Ubuntu, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';` 
instead of 
`font-family: "Segoe UI VSS (Regular)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", Helvetica, Ubuntu, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`
the problem disappeared and the CSS rule is no longer removed.

[Market place](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator) is already updated.  

New release is available here:
https://www.nuget.org/packages/ReportGenerator/4.0.4
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.4
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.4

**Comment by gfletcherMerc** [comment]
Thanks so much, confirmed working with 4.0.4 from NuGet.

**Comment by knom** [comment]
Wow, great!!
Thanks!
