### ISSUE TITLE
Question - Brackets coverage

### ISSUE THREAD

**Issue by ful-stackz** [danielpalme/ReportGenerator#181]
Hello!

I am using OpenCover + ReportGenerator and something in the output is bugging me. Methods that do not return a value have their closing bracket highlighted as _covered line_, whereas methods that do return a value do not have their closing bracket highlighted. These images will explain it better:

![non-return-1](https://user-images.githubusercontent.com/28789098/49437647-5f533100-f7bc-11e8-89c2-6486d3cf8d9f.PNG)
![non-return-2](https://user-images.githubusercontent.com/28789098/49437648-5f533100-f7bc-11e8-9db2-93b88de6f230.PNG)
![return-1](https://user-images.githubusercontent.com/28789098/49437650-5f533100-f7bc-11e8-8e4f-277520bd8f15.PNG)
![return-2](https://user-images.githubusercontent.com/28789098/49437651-5f533100-f7bc-11e8-9587-c6969c7c22ca.PNG)

I wonder why that is? I guess the execution of a `void` method ends with the bracket and the execution of a type-returning method ends with the `return` statement?

Could you, please, shed some light onto this?

**Comment by danielpalme** [comment]
_ReportGenerator_ just displays the coverage information from the coverage XML files.
If a line is covered there, _ReportGenerator_ will mark it as covered otherwise not.
_ReportGenerator_ does not analyze the content of the source code file.

Here's a sample coverage file:
https://github.com/danielpalme/ReportGenerator/blob/master/src/Testprojects/CSharp/Reports/OpenCover.xml#L996, the `vc` attribute contains the coverage state for each statement/line.

**Comment by ful-stackz** [comment]
Thank you very much for the quick response! I guess the issue is related to OpenCover then. Thanks again and have a nice day!
