### ISSUE TITLE
Provide a way to surface Cobertura results as-is in the html report

### ISSUE THREAD

**Issue by Blackbaud-ShaydeNofziger** [danielpalme/ReportGenerator#206]
Currently, the generated html Code Coverage view reports Line Coverage statistics as a percentage of coverable lines. This can be confusing when used in conjunction with Azure Pipeline tasks like "Build Quality Checks Code coverage" that rely on the stats reported in the `coverage.cobertura.xml` file.

For example, suppose you have a build checking for Code Coverage >= 80%, and you get the following results in the code coverage generated report:

| Key | Value |
| -- | -- |
| Covered Lines | 77 |
| Uncovered Lines | 13 |
| Coverable Lines | 90 |
| Total Lines | 365 |
| Line Coverage | 85.5% |

The "Build Quality Check Code Coverage" task, however, looks directly at the cobertura report stats, which are:

| Key | Value |
| -- | -- |
| lines-covered | 87 |
| lines-valid | 117 |
| line-rate | 0.744 |

It seems ReportGenerator disagrees with Cobertura and is calculating the "coverable lines" metric differently from the "lines-valid" value in the report.

Can you provide a reasonable explanation for this? If these values are calculated differently, it would be nice to have the option for the cobertura results to be displayed as-is so that they are consistent with other tools that rely on the cobertura xml report.

**Comment by danielpalme** [comment]
Which tool are you using to generate the cobertura file?

**Comment by Blackbaud-ShaydeNofziger** [comment]
Specifically, the .NET Core test task, with the arguments below.

```
dotnet test ./test/**/*.csproj --configuration 'Release' /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=[path to testresults coverage directory]
```

**Comment by danielpalme** [comment]
So you using [coverlet](https://github.com/tonerdo/coverlet). I don't know how _coverlet_ calculates this metric.
ReportGenerator calculates it in the following way:
Line coverage is "covered lines" divided by "coverable lines" and coverlet seems to have another definition.

I won't change the calculation in _ReportGenerator_ since this would produce other inconsistencies in _ReportGenerator_.

One way to work around this:
_ReportGenerator_ is also able to generate _Cobertura_ files. Those are consistent with the HTML report.
Maybe that's an option for you to use that instead of the file generated by coverlet.

**Comment by Blackbaud-ShaydeNofziger** [comment]
Okay, that makes sense - It was difficult to discern where the discrepancies were coming from. I'll dig more into how coverlet is calculating these and see if we can't configure it differently. And will also consider using ReportGenerator to generate the Cobertura files themselves.
