### ISSUE TITLE
Report generation fails in linux when quotes are used

### ISSUE THREAD

**Issue by nigurr** [danielpalme/ReportGenerator#225]
Hi,

When we are invoking report generator from pipeline in linux, the argument parsing is not correct

This seems to be an issue here https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Program.cs#L20

The actual values of args
```
"\"-reports:abc.xml\"",
"\"-targetdir:/temp\""
```
The end values are `abc.xml\` and `/temp\` after regex matching is done, which is breaking the report generation

**Comment by danielpalme** [comment]
Can you please share the full command you are executing?

Something like the following should work:
```
dotnet ReportGenerator.dll -reports:abc.xml -targetdir:/temp
```

**Comment by nigurr** [comment]
@danielpalme 

This is for windows which works fine
`[command]"C:\Program Files\dotnet\dotnet.exe" ReportGenerator.dll "-reports:E:\AgentPool\LocalAgent\_work\5\s\**\coverage.xml" "-targetdir:E:\Temp\html" "-reporttypes:HtmlInline_AzurePipelines"`

This is for linux which fails

`[command]/usr/local/share/dotnet/dotnet ReportGenerator.dll "-reports:/Users/nigurr/Downloads/_work/1/s/**/coverage.xml" "-targetdir:/temp/html" "-reporttypes:HtmlInline_AzurePipelines"`

**Comment by danielpalme** [comment]
Command line parsing is not as simple as it seem's to be.
See this [article](https://weblogs.asp.net/jongalloway/_5B002E00_NET-Gotcha_5D00_-Commandline-args-ending-in-_5C002200_-are-subject-to-CommandLineToArgvW-whackiness) for some details.

The line `args = args.Select(a => a.EndsWith("\"", StringComparison.OrdinalIgnoreCase) ? a.TrimEnd('\"') + "\\" : a).ToArray();` was introduced to support trailing `\`.
E.g. if you use the following command line parameter "-targetdir:DirectoryWithTrailingSlash\\" it get's interpreted as `-targetdir:DirectoryWithTrailingSlash\` instead of `-targetdir:DirectoryWithTrailingSlash"`.

I will merge your PR. I tested some sample inputs and everything still seems to work on Windows as well.

**Comment by nigurr** [comment]
@danielpalme, thanks. Can you please release package and close the issue?

**Comment by danielpalme** [comment]
Sure. New release will be available soon. I'll let you know.

**Comment by danielpalme** [comment]
New release 4.1.1 is available now.
