### ISSUE TITLE
Source folders are not accepted for all Reporters

### ISSUE THREAD

**Issue by nigurr** [danielpalme/ReportGenerator#233]
Hi,

Few of the reporters support sources folder path and honors it - Jaoco - https://github.com/danielpalme/ReportGenerator/blob/5478fc4138b877fd9ae2db6960934e29118caca3/src/ReportGenerator.Core/Parser/CoverageReportParser.cs#L194

While report formats like Cobertura doesn't honor them - https://github.com/danielpalme/ReportGenerator/blob/5478fc4138b877fd9ae2db6960934e29118caca3/src/ReportGenerator.Core/Parser/CoverageReportParser.cs#L236

Request for change:
1. Irrespective of reporter type, if user specifies/gives source path, include it in one of the possibilies and resolve the correct path.
2. This is required for docker container scenarios where tests/coverage reports can be generated inside container, however actual reporting can be used in Host system which has different path.

This also brings consistency to design

**Comment by danielpalme** [comment]
Hi,

the source directories are used by:
https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Parser/Preprocessing/CoberturaReportPreprocessor.cs#L78

https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Parser/Preprocessing/CoberturaReportPreprocessor.cs#L78

https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Parser/Preprocessing/JaCoCoReportPreprocessor.cs#L86

The reason for that behavior is:
These tools use relative paths in the corresponding XML files.

All the other formats use absolute paths.
I understand that you need that feature for execution in a Docker container.
But it's not trivial to implement that in an efficient way.
If you have to map a absolute path to another path, the problem is to find the right segment in the path where you have to combine the two paths.

**Comment by nigurr** [comment]
@dan

**Comment by acesiddhu** [comment]
@danielpalme does it make sense to have user input may be regex pattern or a simple pattern that needs to be overriden with path user gives. Just a thought.

**Comment by danielpalme** [comment]
I have been thinking about this for a while now.
IMO _ReportGenerator_ should not be responsible to fix the relative paths.
Fixing the paths can be accomplished by preprocessing the coverage files with a script.

Example:
```powershell
(gc "coverage.xml") | % { $_ -replace "C:\invalid\path", "C:\correct\path" } | Out-File "coverage.xml" -Encoding UTF8
```

**Comment by marscher** [comment]
Figuring out a common substring shouldn't be that hard, right? It renders the tool useless for all absolute path reporting tools. Since it is being used in Azure-pipelines to generate reports, it should be reconsidered to support this.

**Comment by danielpalme** [comment]
> Figuring out a common substring shouldn't be that hard, right?

It depends. If there is only **ONE** common directory, you are right.
But there also cases where several base paths exist. Choosing the correct _source directory_ for each _base path_ can be difficult, since a file with the same name might exist in several directories.

I'm not sure if this can be solved without causing other issues.
In the simple scenario from above, you can archive this with a [powershell command](https://github.com/danielpalme/ReportGenerator/issues/233#issuecomment-495345243).

**Comment by danielpalme** [comment]
As this was requested again in #290, I will try to add support for this.
Please go to #290 for any updates on this issue.
