### ISSUE TITLE
Generate relative paths

### ISSUE THREAD

**Issue by soutchilin** [danielpalme/ReportGenerator#238]
Hi,

I really like the tool. 

I'd like to run the report generator during the TFS CI Build. This is for developers with Visual Studio Professional license. They should be able to download the report (HTML files) and open them e.g. for the locally stored files of the same branch. Because in the HTML the absolute path to the .cs files is stored, it is not possible OOTB. Does it makes sense to enhance the ReportGenerator in that direction?

Regards,
Alexander

**Comment by danielpalme** [comment]
Hi Alexander,

this not as easy as it seems to be.
The problem is, that a report can be generated out of several coverage files.
Each coverage files can contain classes from another drive.
In such a scenario it would not be easy to figure out the correct relative path.

I guess the developers are able to figure out their local path.
