### ISSUE TITLE
[xmlSummary] Linecoverage tag contains extra info

### ISSUE THREAD

**Issue by nikosatwork** [danielpalme/ReportGenerator#256]
Hi Daniel,

`Linecoverage` tag includes information about `coverable lines` and `total lines` too. 

i.e. ```<Linecoverage>25.7% (583 of 2267)</Linecoverage>```

I believe it should only show the (percentage) number, and ideally without the % symbol too

What are you thoughts on this?

Thanks

**Comment by danielpalme** [comment]
Hi @nikosatwork 

why should the '%' symbol get removed? The value is a percentage and therefore it should be present.
Otherwise one could think it's an absolute value.

The line coverage tag includes `Covered lines` and `Coverable lines` (not `total lines`).  
Reason: This makes it obvious how the value is calculated. It it important to see, that not the `total lines` are used.

**Comment by nikosatwork** [comment]
`TextSummary` and `CsvSummary` contain just the percentage, not the lines covered information, in their LineCoverage equivalent tags 

A use case we would like to explore is parsing this file (XmlSummary) and store the `Linecoverage` value to a database. Currently that would require to strip the string after and including %

**Comment by danielpalme** [comment]
Sorry, I did not pay attention to `XmlSummary`.
It makes sense to change this behavior.

**Comment by danielpalme** [comment]
Fixed with new release:
https://www.nuget.org/packages/ReportGenerator/4.2.2

**Comment by nikosatwork** [comment]
Thank you Daniel!
