### ISSUE TITLE
Icov.info file from flutter

### ISSUE THREAD

**Issue by jkyon** [danielpalme/ReportGenerator#269]
Hi
I´m currently creating a CI for our flutter app on Azure DevOps, and we need to display the code coverage from or flutter tests.

The file generated by flutter coverage is calle "Icov.Info". Is there a way to read this file using ReportGenerator?

I tried it, but the task failed.

Thank you in advance

**Comment by danielpalme** [comment]
Since the file is named "lcov.Info" I guess that the coverage file is in [lcov format](https://github.com/linux-test-project/lcov).

Maybe the _lcov_ file does not match the structure that _ReportGenerator_ expects.
If you could share the your coverage file (not your source code), I can have a look at the problem and try to add support for this format.

You can send the file by email: danielpalme82@gmail.com

**Comment by jkyon** [comment]
Hi Daniel

I had sent the file to you.

Thank you in advance

**Comment by danielpalme** [comment]
Will have a look at it within the next days.

**Comment by danielpalme** [comment]
New release 4.2.10 should be available on Azure DevOps within a couple of minutes.
