### ISSUE TITLE
History report only showing earliest coverage 

### ISSUE THREAD

**Issue by DavidVivash** [danielpalme/ReportGenerator#3]
The new history graphs look like they'd be really good, however I can't seem to get them to work.
I've specified the history directory in the command line, and I can see the xml file being created in that folder (and I've run the report generator multiple times, so have multiple xml files in the history folder), but when I look at the graph it only shows the markers for the earliest coverage report.
I've tried deleting out some of the files etc. (to see if it's just a bad file in there), but no matter what I do I still only get the markers on the graph for the earliest coverage data in the history folder.

**Comment by danielpalme** [comment]
This is probably by design, but it's not yet documented anywhere.
The chart events are filtered in the following way:
- If the coverage data between two events did not change, then only the first event is shown. As soon as you make real changes to the code base, then you will see more events in the chart. One of the following properties has to change:
  - CoveredLines
  - CoverableLines
  - TotalLines
  - CoveredBranches
  - TotalBranches
- Only the latest 100 of those events are shown

**Comment by DavidVivash** [comment]
Thanks, this is correct, having made some code changes I can now see the history lines as expected.
