### ISSUE TITLE
Report Generator Null Reference

### ISSUE THREAD

**Issue by jpedretti-ciandt** [danielpalme/ReportGenerator#350]
We are using Azure devops for our Android project and noticed that the task PublishCodeCoverageResults couldn't load Jacoco's XML file with a null reference error. I opened an issue developer community in visual studio and they concluded that the problem is with the generator. [Issue link](https://developercommunity.visualstudio.com/content/problem/1020371/publishcodecoverageresults-fails-to-load-jacoco-xm.html#).

<img width="1322" alt="133222-screen-shot-2020-05-06-at-170224" src="https://user-images.githubusercontent.com/56452294/83140629-c0637880-a0c4-11ea-9433-a5a3726e5856.png">

The XML that they used to investigate is attached too.

[134263-testusqaunittestcoveragexml.zip](https://github.com/danielpalme/ReportGenerator/files/4695443/134263-testusqaunittestcoveragexml.zip)

Thanks for the help.

**Comment by danielpalme** [comment]
Will have a look soon.

**Comment by danielpalme** [comment]
This issue is already fixed (see #300 
The _PublishCodeCoverageResults_ task uses an old version of _ReportGenerator_.

You could use use my [Azure DevOps extension](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator) to generate the HTML report and disable the regeneration within the _PublishCodeCoverageResults_ task with the following environment variable:
```
disable.coverage.autogenerate: 'true'
```

**Comment by jpedretti-ciandt** [comment]
Thanks, and sorry for the trouble.
