### ISSUE TITLE
Show branch stats, not just percentages

### ISSUE THREAD

**Issue by sixeyes** [danielpalme/ReportGenerator#364]
The coverage report summary screen shows the branch coverage % for each file. Unfortunately due to async statements in my code I end up with some branches I can't cover. For a particular file I know that 3 branches aren't covered. As I add code to the file it would be really useful if I could see those statistics (covered branches / total branches). This way I would know if they differed by 3 I'd covered all the other branches from the summary page. I realise there isn't much room on the report, so I'd be happy with 29/32 90%.

Earlier today the branch coverage for the file was 25/29 86% and it wasn't obvious I hadn't covered one of the branches but there is a difference of 4, (which can be determined from the statistics when clicking on a file but not on the summary screen).

In fact while writing this I realise that if space is tight, just reporting the number of uncovered branches for each file would give me what I'm after.

I'm using VS2019, AltCover and .NET v4.7.2 if that makes any difference.

![image](https://user-images.githubusercontent.com/604902/88947738-db02cb00-d288-11ea-89d6-66eaa311fb8a.png)

**Comment by danielpalme** [comment]
In general a good idea. The problem is the limited space.

Would a tooltip be helpful for you?

**Comment by sixeyes** [comment]
A tooltip would be good.

If the number of uncovered branches is on the summary, the number changing would get my attention where a tooltip would not.

Perhaps it should only be shown if there are uncovered branches.
Could it be added in the area I circled? Perhaps the number could be left justified, so it's up against the line coverage  bar?
Could it only appear if there's a command line option?

**Comment by danielpalme** [comment]
I can't add it to the circled area. That's used for the history chart:
![image](https://user-images.githubusercontent.com/859606/88960244-8456ba80-d2a3-11ea-9e2f-eda2ba053fbf.png)

I have always tried to keep the number of possible command line parameters as small as possible and only added new parameters, when I was convinced that they are easy to understand and useful for the majority of the users.
Otherwise _ReportGenerator_ would end up with (too) many parameters that no one understands.

I'm not sure if this parameter is really useful for the majority of the users.

**Comment by sixeyes** [comment]
What do I have to do to see the history chart?

I guess I'm going to ask for a tooltip as it's better than nothing. I do understand the issue with command line parameters.

How about an environment variable :)

**Comment by danielpalme** [comment]
To see the history add the `-historydir:YOUR_PERSISTENT_DIRECTORY` command line parameter.

Environment variables are even worse :-) They are not discoverable.

**Comment by sixeyes** [comment]
Perhaps the uncovered branch count could appear in the area reserved for the history chart if that's not been requested?

So if -historydir is not present it could show the number of uncovered branches (if greater than zero)?

If -historydir is present, it's only available as a tooltip?

**Comment by danielpalme** [comment]
Release 4.6.3 adds the tooltips.

I don't like the idea with `-historydir`. If the history flag is not set, a "random" number would appear and it wouldn't be obvious how to interpret that number.

Perhaps I'm added two additional columns to the table in the future. Still a space problem. But at least it would be easy to understand.

**Comment by sixeyes** [comment]
Could there be a command line option to change % values to fractions?

Instead of seeing 88.5%, it would show 23/26. 

BTW I've just downloaded v4.6.4 but I can't see any tooltips in the report. Using Firefox v79.0. Do I need to change my configuration?

**Comment by danielpalme** [comment]
Tooltip works fine for me with Firefox:
![image](https://user-images.githubusercontent.com/859606/89184914-b87af580-d599-11ea-8781-18d71f797f9c.png)

Sample reports: https://github.com/danielpalme/ReportGenerator/blob/master/docs/resources/SampleReports.zip

I thinking about a radio button to switch between percentage / ratio.
But will take a while, since I'm on vacation.

**Comment by sixeyes** [comment]
OK. I can see them now. Apparently I have to stop moving the mouse before Firefox will show them.

Radio button sounds good. Have a great time on holiday.

**Comment by danielpalme** [comment]
I finally added two additional columns in release 4.6.5:
https://www.nuget.org/packages/ReportGenerator/4.6.5

**Comment by sixeyes** [comment]
Thanks very much. Just tried it, it's perfect :)
