### ISSUE TITLE
reportgenerator cannot be used in build pipeline for .net framework

### ISSUE THREAD

**Issue by daveheena** [danielpalme/ReportGenerator#370]
My build pipeline uses powershell script to generate xml report. I want to convert XML report in HTML report but I cannot do so without absolute path of exe for .NET Framework application. I do not have absolute path of exe while executing script from pipeline.

**Comment by danielpalme** [comment]
It depends which package you are using.

Please have a look at
https://www.nuget.org/packages/ReportGenerator
or
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool

If you use the [global tool](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool), you don't need an absolute path.
If you are using the "regular" [package ](https://www.nuget.org/packages/ReportGenerator), you can use one of these an absolute path:
```
dotnet $(UserProfile)\.nuget\packages\reportgenerator\x.y.z\tools\netcoreapp3.0\ReportGenerator.dll [options]
$(UserProfile)\.nuget\packages\reportgenerator\x.y.z\tools\netcoreapp3.0\ReportGenerator.exe [options]
$(UserProfile)\.nuget\packages\reportgenerator\x.y.z\tools\net47\ReportGenerator.exe [options]
```

See also:
https://github.com/danielpalme/DotNetCoverageToolComparision/blob/master/run.bat

**Comment by egraff** [comment]
Another option is to use `$(NuGetPackageRoot)` instead of `$(UserProfile)\.nuget`. However, this only works if

 * the .NET Framework project file is a new-style csproj, and
 * ReportGenerator is run in context of an msbuild target of a specific csproj project (`$(NuGetPackageRoot)` is defined in the `.csproj.nuget.g.props` file generated for a project in its obj/ folder after running either `nuget restore` or `dotnet restore`).

The benefit is that this would work even when the NuGet package root is pointed elsewhere than the default user nuget folder (e.g. if configured using nuget.config).

Yet another option (but this might be a hack, as I don't know if this is relying on a documented mechanism) is to use the `$(PkgReportGenerator)` property, which would point at the `reportgenerator\x.y.z` folder - but in addition to the restrictions above, this would only work for csproj projects where the ReportGenerator "regular" package is included.
