### ISSUE TITLE
Performance with a large number of classes

### ISSUE THREAD

**Issue by richardgavel** [danielpalme/ReportGenerator#375]
I'm dealing with rendering an HTML report with over 16K classes and it's really slow. For each class, you are running the renderers in parallel, but you aren't rendering each class in parallel. Wouldn't that realistically be more valuable?

https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Reporting/ReportGenerator.cs#L89

**Comment by danielpalme** [comment]
I already tried parallel processing for classes as well. There was not a big performance improvement.
Reason: For the HTML report some sections of the generation need to be locked, since some overall information has to be collected for the summary report.

I guess that your problem is slow IO:

- Are your class files located on your disk (HDD vs SSD) or on a network share or remote (e.g. Github)?
- How long does the report generation take in your case (total time)?

**Comment by richardgavel** [comment]
I end up with about 16000 HTML files. This is on my local machine with SSD. It takes roughly 10-15 minutes.

**Comment by danielpalme** [comment]
This seems really slow. Should probably work within a minute.
Is it possible to share your coverage file? You can send it by email (reportgenerator@palmmedia.de).
I do **not** need the source code.
