### ISSUE TITLE
Release 4.8.6 does not produce accurate coverage reports for generic classes anymore

### ISSUE THREAD

**Issue by rokeller** [danielpalme/ReportGenerator#408]
As of the latest release of the global tool (4.8.6), reports generated for generic classes are no longer accurate.

Console output of ReportGenerator:
2021-03-04T10:59:40: Arguments
2021-03-04T10:59:40:  -reports:D:\GitSrc1\common\Common.Data\\Coverage\Temp\**\coverage.cobertura.xml
2021-03-04T10:59:40:  -reporttypes:HtmlInline_AzurePipelines_Dark
2021-03-04T10:59:40:  -targetdir:D:\GitSrc1\common\Common.Data\\Coverage
2021-03-04T10:59:40:  -assemblyfilters:-*.Tests
2021-03-04T10:59:40:  -filefilters:-*.g.cs
2021-03-04T10:59:42: Writing report file 'D:\GitSrc1\common\Common.Data\\Coverage\index.html'
2021-03-04T10:59:43: Report generation took 2.9 seconds

It looks like _all_ classes with generic type parameters are affected by this. However, the below minimal class and test easily show the problem too:

```csharp
public class GenericClass<T>
{
    public string GetType()
    {
        return typeof(T).FullName;
    }
}
```

```csharp
using Xunit;

public class GenericClassTests
{
    [Fact]
    public void ItWorks()
    {
        Assert.Equal("System.Int32", new GenericClass<int>().GetType());
    }
}
```
While the test does succeed and clearly covers the code, the generated report does report 0 uncovered lines, but also reports 0 covered lines which is clearly wrong.

**Comment by danielpalme** [comment]
Sorry for that.
I fixed it in release 4.8.7.

**Comment by rzikm** [comment]
It seems to me that the issue has resurfaced again (report-generator-cli  5.1.3.0), can you please look into it, @danielpalm?

**Comment by danielpalme** [comment]
@rzikm 
I did not change handling of generic classes.
Do you have a concrete example which I can use to reproduce your problem?

**Comment by rzikm** [comment]
I can reproduce this with the same code as rokeller posted above, but basically:

- extract [reportgeneratorbug.zip](https://github.com/danielpalme/ReportGenerator/files/8358124/reportgeneratorbug.zip) somewhere
- cd into `reportgeneratorbug/UnitTests`
- `dotnet-coverage collect "dotnet test" -f cobertura`
- `reportgenerator -reports:.\output.cobertura.xml -targetdir:report -reporttypes:html`

**Comment by danielpalme** [comment]
Thanks for the example. Will have a look.

**Comment by danielpalme** [comment]
If you use `dotnet-coverage collect "dotnet test" -f cobertura` the coverage file contains:
```xml
<class line-rate="1" branch-rate="1" complexity="1" name="DotnetSandbox.GenericClass&lt;T&gt;" filename="Program.cs">
```

If you use `dotnet test --collect:"XPlat Code Coverage"` instead the coverage file contains:
```xml
<class name="DotnetSandbox.GenericClass`1" filename="Program.cs" line-rate="1" branch-rate="1" complexity="1">
```

So with `dotnet-coverage` the class name contains `<T>` and the the class gets filtered out by https://github.com/danielpalme/ReportGenerator/blob/879cd04b0abc1f0ac7814ee231aeb13152b6f2a2/src/ReportGenerator.Core/Parser/CoberturaParser.cs#L127

This won't be easy to fix. I can't just remove `&& !name.Contains("<")`, because this will list too many compiler generated classes:
Some examples from https://github.com/danielpalme/ReportGenerator/blob/main/src/Testprojects/CSharp/Reports/Cobertura_dotnet-coverage.xml:
- Test.Program.&lt;CallAsyncMethod&gt;d__1
- Test.AsyncClass.&lt;SendAsync&gt;d__0
- Test.TestClass2.&lt;&gt;c
- Test.TestClass2.&lt;&gt;c__DisplayClass14_0

**Comment by rzikm** [comment]
I see, thanks for the info about `dotnet test --collect:"XPlat Code Coverage"`. It will actually work better for my use case since it lists only classes from my code.

Just an idea, maybe you might be able to differentiate between compiler-generated classes and regular classes by checking where the <> chars occur. My guess is that compiler-generated classes start with '<' (which generics don't) and never end with '>' (which generics do).

**Comment by danielpalme** [comment]
No need to file a separate issue. Will have a look within the next days.

**Comment by danielpalme** [comment]
@rzikm 
I improved the filtering in release 5.1.4.
