### ISSUE TITLE
Can't override `targetdir` from `.netconfig` via cli

### ISSUE THREAD

**Issue by viceice** [danielpalme/ReportGenerator#509]
**Describe the bug**
Can't override `targetdir` from `.netconfig` via cli. I need to override the `targetdir` via cli argument on CI, but that doesn't seem to work as expected.

`reporttypes` works as expected.

**To Reproduce**

if have this `.netconfig`
```ini
[ReportGenerator]
  reports = "**/TestResults/*/coverage.*.xml;coverage/**/cobertura-coverage.xml"
  targetdir = ".coverage/"
  reporttypes = "TextSummary;Cobertura;Html"
  historydir  = ".coverage/history/"
```

and need to run report generator on ci as
```sh
> dotnet reportgenerator -reporttypes:TextSummary;Cobertura -targetdir=coverage/
 Arguments
  -reporttypes:TextSummary;Cobertura
  -targetdir=coverage/
 Reading historic reports
 Writing report file '.coverage/Cobertura.xml'
 Writing report file '.coverage/Summary.txt'
 Creating history report
 Report generation took 0.3 seconds
```

**Comment by viceice** [comment]
No hurry, I've found another solution as workaround. But it's a bug and should be fixed. 🤗

**Comment by danielpalme** [comment]
The code seems to be correct:
https://github.com/danielpalme/ReportGenerator/blob/bf487cba56912ff5b5ab4bb1d35d1336dbe2151f/src/ReportGenerator.Core/ReportConfigurationBuilder.cs#L64

The command line argument takes precedence.

Please have a look at your command line arguments.
Use `dotnet reportgenerator -reporttypes:TextSummary;Cobertura -targetdir:coverage/` instead of `dotnet reportgenerator -reporttypes:TextSummary;Cobertura -targetdir=coverage/` (note the ':' instead of the '='), then it should work for you.

**Comment by viceice** [comment]
🤦‍♂️ ok, too simple. probably because most other tools expect `=` as separator.
