### ISSUE TITLE
Why does the Html report create two index files?

### ISSUE THREAD

**Issue by silkfire** [danielpalme/ReportGenerator#524]
Is there a particular reason why the Html report creates two identical index files, i.e. `index.htm` and `index.html`? I'm quite sure one is sufficient.

![image](https://user-images.githubusercontent.com/1554615/169701907-f3a99427-c231-4b30-a167-467ad915d164.png)

**Comment by danielpalme** [comment]
Yes in theory, one file would be enough.
In the beginning there was only a `htm` file.
But sometimes the report is published on a webserver which only has the `html` file as a default document.
In order to not break anybody's workflow relying on the `htm` file to be present, both files do exist.
You can ignore one of them :-)
