### ISSUE TITLE
Discrepancy in %coverage shown by report generator vs visual studio 2015

### ISSUE THREAD

**Issue by decentshakti** [danielpalme/ReportGenerator#54]
We used report generator to generate html report for coverage generated by VS(Visual Studio 2015 Enterprise).
VS shows different coverage(see snapshot) than report generated by report generator(see snapshot).
The .coverage file is same for both. 
VS uses "codecoverage.exe" to generate .xml. So, we use the same to generate .xml (using command line). So, the .xml file is also same for both.

Report Generator Snapshot: (Line Coverage = 60.1%)
![capture](https://cloud.githubusercontent.com/assets/8180193/17052884/fcf38864-501c-11e6-8268-7a9670367141.JPG)
VS Snapshot: (Line Coverage = 58.59%)
![capture](https://cloud.githubusercontent.com/assets/8180193/17052898/0cc29442-501d-11e6-94e2-20d7956a900e.JPG)

Please look into the issue.

**Comment by danielpalme** [comment]
Please see this thread for an explanation:
http://reportgenerator.codeplex.com/discussions/549025

**Comment by decentshakti** [comment]
Thanks for the reply!
But as shown in the snapshot, VS also shows Line coverage?

**Comment by danielpalme** [comment]
Yes the numbers are a bit different. I don't know exactly how VS counts lines here.
ReportGenerator counts files twice if two classes are defined in a single file. That may explain the difference.

Without a concrete example I can't tell. If you find a concrete class or line where ReportGenerator shows an invalid coverage, please create an issue with corresponding screenshots or reports attached.

**Comment by adam990i** [comment]
```
Please see this thread for an explanation:
http://reportgenerator.codeplex.com/discussions/549025
```
@danielpalme: Unfortunately, link is not longer available. Can you share the explantation here?

**Comment by danielpalme** [comment]
@adam990i 
VS uses blocks, see some explanation here: http://stackoverflow.com/questions/4958209/the-blocks-in-code-coverage-with-vs2010 
ReportGenerator maps this to the lines of the source code and therefore shows "line coverage". 

Since blocks and lines are not the same, the results may differ (23,70% <-> 25.29% coverage). 

ReportGenerator parses all source files to generate the reports. If one file does not exist (any more), the corresponding warning is generated. 
If you want an accurate report, all files should be available.
