### ISSUE TITLE
Report builder that throws an exception does not result in failed generation

### ISSUE THREAD

**Issue by MarcelVersteeg** [danielpalme/ReportGenerator#554]
**Describe the bug**
When a report builder, for example a custom report builder plugin, throws an exception during the generation, this does not lead to a program's exit code other than 0 indicating the execution failed.

**To Reproduce**
The following input helps to reproduce your issue:
1. Create a new plugin, implementing the `IReportBuilder interface`
2. Implement the required method simply by throwing an exception (e.g. the `NotImplementedException`).
3. Use the new plugin to generate a coverage report
4. In the output of the ReportGenerator.Console application, you will see messages like `Error during rendering report for class...`, but the exit code of the application is still `0`, indicating a success.

**Comment by danielpalme** [comment]
This is a tough one.
I totally understand your point.

But there are other users with different expectations.

Report generation can fail because of different reasons. E.g.
- Bug in plugin
- Error when reading (remote) code file
- etc.

In your case the exit code should not be 0, because it's a general error.
But that's hard to distinguish from an error that may only exist temporarily (e.g. file not available).

Most users don't want to fail the complete build, just because a single file is not accessible.

**Comment by danielpalme** [comment]
> Isn’t an exception thrown in a plug-in not the same as a bug in a plug-in? Exceptions, like a NullReferenceException for example, usually are because of a bug in the plug-in.

Yes, that's the same.

> I understand that you don’t want to fail a generation when a file is missing or whatever… Are there exceptions that would cause the generation application to exit with a non-zero exit code?

Yes, if an exception occurs at any other point in the execution. Only exceptions that happen during report rendering are ignored.
