### ISSUE TITLE
Markdown - collapsing lines

### ISSUE THREAD

**Issue by leahy268** [danielpalme/ReportGenerator#567]
Hi,

I have been using your report generator for GitHub action.  Which works wonderfully thank you.  

However I would love to be able to collapse the lines in Markdown.  It would make it much more readable.

See below:

<details><summary>ComponentLibrary</summary>
<p>ComponentLibrary,Function1</p>
<p>ComponentLibrary.Function2</p>
</details>

**Comment by danielpalme** [comment]
Looks great here on GitHub.
But I'm not sure how other Markdown parsers will handle those custom elements.

**Comment by leahy268** [comment]
Unfortunately at the moment the default MarkDown is unusable as currently the lines are far too wide for gitHub to handle.  This means for users to actually see the full comment they have to kind of click on a line and drag to the right to see the actual coverage and then drag back.

![image](https://user-images.githubusercontent.com/58454534/206046733-bebdb8b3-06c2-4ba6-81fd-d23a78f0250c.png)

**Comment by danielpalme** [comment]
Since the current `MarkdownSummary` is to wide for GitHub, I plan to implement a new report type named `MarkdownSummaryGithub`. This report has fewer columns and long class names a splitted into several lines.

Here's a sample with my current implemenation.
What do you think?

# Summary
<details open><summary>Summary</summary>

|||
|:---|:---|
| Generated on: | 08.12.2022 - 23:07:56 |
| Parser: | OpenCover |
| Assemblies: | 1 |
| Classes: | 17 |
| Files: | 15 |
| **Line coverage:** | 63.6% (121 of 190) |
| Covered lines: | 121 |
| Uncovered lines: | 69 |
| Coverable lines: | 190 |
| Total lines: | 508 |
| **Branch coverage:** | 62.5% (5 of 8) |
| Covered branches: | 5 |
| Total branches: | 8 |
| **Method coverage:** | 57.6% (30 of 52) |
| Covered methods: | 30 |
| Total methods: | 52 |

</details>

## Coverage
<details><summary>Assembly 1 - 63.6%</summary>

|**Name**|**Line**|**Branch**|**Method**|
|:---|---:|---:|---:|
|**Assembly 1**|**63.6%**|**62.5%**|**57.6%**|
|Test.AbstractClass|100%||100%|
|Test.AbstractClass_SampleImpl1|50%||33.3%|
|Test.AbstractClass_SampleImpl2|50%||33.3%|
|Test.AbstractGenericClass`2|0%||0%|
|Test.AnalyzerTestClass|0%||0%|
|Test.AsyncClass|100%||100%|
|Test.ClassWithExcludes|100%||100%|
|Test.CodeContract_Contract|0%||0%|
|Test.CodeContract_Target|100%|100%|100%|
|Test.GenericClass`2|100%||100%|
|Test.PartialClass|54.5%|50%|50%|
|Test.PartialClassWithAutoProperties|66.6%||80%|
|Test.Program|79.5%||66.6%|
|Test.SomeClass|100%||100%|
|Test.SomeModel||||
|Test.TestClass|57.1%|50%|50%|
|Test.TestClass2|63.1%|50%|60%|
|Test.TestClassWithAVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVer<br>yLongLongName|63.1%|50%|60%|

</details>

<details><summary>Assembly 2 - 63.6%</summary>

|**Name**|**Line**|**Branch**|**Method**|
|:---|---:|---:|---:|
|**Assembly 2**|**63.6%**|**62.5%**|**57.6%**|
|Test.AbstractClass|100%||100%|
|Test.AbstractClass_SampleImpl1|50%||33.3%|
|Test.AbstractClass_SampleImpl2|50%||33.3%|
|Test.AbstractGenericClass`2|0%||0%|
|Test.AnalyzerTestClass|0%||0%|
|Test.AsyncClass|100%||100%|
|Test.ClassWithExcludes|100%||100%|
|Test.CodeContract_Contract|0%||0%|
|Test.CodeContract_Target|100%|100%|100%|
|Test.GenericClass`2|100%||100%|
|Test.PartialClass|54.5%|50%|50%|
|Test.PartialClassWithAutoProperties|66.6%||80%|
|Test.Program|79.5%||66.6%|
|Test.SomeClass|100%||100%|
|Test.SomeModel||||
|Test.TestClass|57.1%|50%|50%|
|Test.TestClass2|63.1%|50%|60%|
|Test.TestClassWithAVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVer<br>yLongLongName|63.1%|50%|60%|

</details>

**Comment by leahy268** [comment]
That looks heaps better.. When can I start using it 😊

**Comment by danielpalme** [comment]
The next release will contain the new report type.

I will let you know once it's published.

**Comment by EricStG** [comment]
Will there be a Delta version of this, similar to `MarkdownDeltaSummary`?

**Comment by danielpalme** [comment]
Release 5.1.13 has been published.
