### ISSUE TITLE
To combine multi coverage report

### ISSUE THREAD

**Issue by Duraimurugan-jp** [danielpalme/ReportGenerator#615]
I am planning to combine all repos code coverage to show overall coverage report. So I created release pipeline to download all repos build artifact to fetch the code coverage that was already generated by reportGenerator for each individual repo. I have downloaded and can able to see each files with respective repos. Is there way to use already generated *.xml report from each repo to reportGenerator pipeline?

**Comment by danielpalme** [comment]
It's possible, but depending on you code base, it may be difficult.
You can generate coverage XML files in different pipelines (e.g. _Cobertura_ format).
Each pipeline can generate a coverage report based on that file.

If you create a separate pipeline which downloads the artifacts (especially the _Cobertura_ files), you are able to generate a combined report.
In order to get a complete report, the source code of all your pipelines must be available at the same location(s) as in the previous pipelines. This may be difficult, if you have separate code bases in each pipeline.
