### ISSUE TITLE
Risk Hotspots  thresholds -  what are the default values - and how change them

### ISSUE THREAD

**Issue by wzaieddev** [danielpalme/ReportGenerator#628]
Hi,
i'm using  ReportGenerator version 5.1.23.0 , i have installed it globaly with this comand 
 dotnet tool install -g dotnet-reportgenerator-globaltool
and i generate the report using  reportgenerator   -reports:"..." etc. 
and all work fine.

on your documentation i found this
Risk Hotspots
Based on the [metrics](https://reportgenerator.io/) you get a list of potential risk hotspots.
The following metrics are analyzed if available, the warning thresholds are configurable:

[Cyclomatic complexity] 
[NPath complexity] 
[Crap score] 

i have two questione:
what are the default values ?
 and how change them?

Best Regards

**Comment by danielpalme** [comment]
You can finde the default values here:
https://github.com/danielpalme/ReportGenerator/wiki/Settings#risk-hotspots

The wiki page also explains which command line parameters you have to use in order to override the default values.

If the metrics are available depends on the coverage tool you are using.
