### ISSUE TITLE
Unable to convert opencoverxml file into corbertura.xml file using ReportGenerator in Azure Devops Pipeline

### ISSUE THREAD

**Issue by SatheshSelvaraj** [danielpalme/ReportGenerator#656]
Hi All,

We are working on TSQL code coverage, and successfully generated the opencoverxml file using powershell task. But we are unable to convert the opencoverxml file into cobertura file to publish into SonarQube report, its missing with line of coverage data while using the report generator tool via Azure DevOps pipeline. Can you please assist on  this request.

**To Reproduce**
The following input helps to reproduce your issue:
1. Console output of ReportGenerator, we have create the task to convert opencoverxml to Cobertura.
<img width="773" alt="Screenshot pipeline task" src="https://github.com/danielpalme/ReportGenerator/assets/163382758/4c6db40a-de6f-428d-9f5d-1baf2f57281f">

post conversion the line of code is not covered and piblished.
<img width="835" alt="image" src="https://github.com/danielpalme/ReportGenerator/assets/163382758/4fc573e7-371c-49c7-97f6-c1e7c4fce4b1">

The output file that we are getting through HTML and XML, but it is unable to convert into Cobertura file using report generated. We can able to publish the code coverage only if it is converted into cobertura.

[HTMLXMfile-correct output.zip](https://github.com/danielpalme/ReportGenerator/files/14597292/HTMLXMfile-correct.output.zip)

2. If the issue is related to a specific coverage file which gets parsed by ReportGenerator, you can share the file:
Opencover XML file send through the Email

**Comment by danielpalme** [comment]
Thanks for your sample files.

The problem is/was that the listed files in the OpenCover file do not exist on disk (e.g. `[dbo].[sp_alterdiagram]`).
Therefore `ReportGenerator` is not able to read the file which resulted in an empty `<lines />` element.

I changed the behavior now. If a file does not exist at least the lines from the OpenCover file are represented in the Cobertura output.

Please try again. And I would be happy if you update your review to 5 stars :-)

**Comment by SatheshSelvaraj** [comment]
Hi danielpalme,

Thank you for your help.
We are able to publish the correct report now.
Much appreciated on your kindly support.

Thanks

**Comment by danielpalme** [comment]
Awesome!
