### ISSUE TITLE
Why is the reportgenerator command installed using the dotent not working?

### ISSUE THREAD

**Issue by JY1990** [danielpalme/ReportGenerator#658]
![image](https://github.com/danielpalme/ReportGenerator/assets/74392941/1ed62d1b-1e94-4a7e-93ea-9384baee67d1)
![image](https://github.com/danielpalme/ReportGenerator/assets/74392941/49eada26-63ff-4f2a-b5cb-eaa0a389cdcb)
![image](https://github.com/danielpalme/ReportGenerator/assets/74392941/b27528f8-ec6f-497a-89b9-82f9e4934597)
Is it because something is missing?

**Comment by JY1990** [comment]
![image](https://github.com/danielpalme/ReportGenerator/assets/74392941/0b665355-d2bf-4ccd-95ed-c6551a3ee4aa)
It is not possible to use the exe directly

**Comment by danielpalme** [comment]
It is possible to use the EXE directly. 
Your are getting an error message because you are using not supported command line parameters.

Are you sure that _ReportGenerator_ is the correct tool for your use case?
_ReportGenerator_ generates code coverage reports.

See here for a usage guide:
https://reportgenerator.io/usage
