### ISSUE TITLE
File '' does not exist (anymore) for all files

### ISSUE THREAD

**Issue by agray** [danielpalme/ReportGenerator#679]
**Describe the bug**
Version 5.3.6 and 5.3.7 is returning File '' does not exist (anymore) for all files.

**To Reproduce**
See  https://github.com/Sauceforge/Saucery/actions/runs/9730705675 and https://github.com/Sauceforge/Saucery/actions/runs/9730705675/job/26854373691

Why is this happening? It used to work.

**Comment by danielpalme** [comment]
I took a look at a previous execution:
https://github.com/Sauceforge/Saucery/actions/runs/9730117672/job/26853064588

Here the same warnings appear (with version 5.3.6).

I think the problem is, that the step `generate-report` in your [pipeline.yml](https://github.com/Sauceforge/Saucery/blob/master/.github/workflows/pipeline.yml), does not contain `- uses: actions/checkout@v4`

I created a [PR](https://github.com/Sauceforge/Saucery/pull/164) to fix this.

**Comment by agray** [comment]
That did the trick.  Thank you.  Weird that I didn't need that step in the past.
