### ISSUE TITLE
.netconfig assemblyfilters not applying multiple

### ISSUE THREAD

**Issue by danpowell88** [danielpalme/ReportGenerator#700]
**Describe the bug**
When using a .netconfig file I specified multiple filters using a single assemblyfilters attribute and it does not appear that they are all working, if i use multiple assemblyfilter attributes that it does work

**To Reproduce**

Using:
Executable: /home/runner/.dotnet/tools/.store/dotnet-reportgenerator-globaltool/5.3.11/dotnet-reportgenerator-globaltool/5.3.11/tools/net8.0/any/ReportGenerator.Core.dll

The following did not exclude all assemblies
```
[ReportGenerator]
	assemblyfilters = -*Test*;-NServiceBus*
```
but the following did
```
[ReportGenerator]
    assemblyfilter = -*Test*
    assemblyfilter = -*NServiceBus*
````

**Comment by danielpalme** [comment]
I will fix this in the next release!

**Comment by danielpalme** [comment]
I found the root cause.
.netconfig files treat `;` as the start of a comment. Therefore `-NServiceBus*` is ignored in your case.

See: https://github.com/dotnetconfig/dotnet-config?tab=readme-ov-file#format

I modified my code. Instead of `;` you will have to use `,` to get it working.
The next release will contain this change.

**Comment by danielpalme** [comment]
Release 5.4.0 is now available!

**Comment by viceice** [comment]
quoting fixes it too
