### ISSUE TITLE
Limit report to subset of the code

### ISSUE THREAD

**Issue by ilengyel** [danielpalme/ReportGenerator#73]
We are looking for a way to produce a targeted report for just the code in a pull request. Primarily to obtain a quick number: %coverage for the pull request (taken from the XMLSummary), but a HTML report of the "diff" would be really nice. Is there a way to provide a diff/patch file to the report generation to only limit showing the interested lines? This could also be an OpenCover question where the patch file filtering could happen wile running the tests.

_Our Environment:_
git -> visual studio -> xunit -> opencover -> reportgenerator

**Comment by danielpalme** [comment]
It should be possible to modify _ReportGenerator_ to only include classes in the report where coverage **changed** since the last run (based on the data generated by the _-historydir_ feature).

But limiting this to the affected lines of a pull request would be quite difficult. _ReportGenerator_ and _OpenCover_ are not aware of any source control systems.

**Idea**: Post process the file generated by _OpenCover_: Remove all `<SequencePoint />` elements that are not affected by pull request. Then use the modified file in _ReportGenerator_. _ReportGenerator_ will the ignore all lines that don't have a corresponding `<SequencePoint />` and mark them as _not coverable_ (gray).

**Comment by ilengyel** [comment]
Thanks for your response daniel, sounds like the idea on filtering out the sequence points will be the way to go. The intention was aways to keep it agnostic from the source control but drive it with a diff file format like [Unified Format](http://www.gnu.org/software/diffutils/manual/html_node/Example-Unified.html#Example-Unified), but I will start with whatever git spits out.

**Comment by ilengyel** [comment]
So it turns out the filtering worked quite well. I wrote a mini tool to strip any unwanted `<SequencePoint />` and `<BranchPoint />`.

For anyone interested in the tool, you can find it here: [CoverageDiff](https://github.com/ilengyel/CoverageDiff)
