### ISSUE TITLE
Same code version is producing different coverage results

### ISSUE THREAD

**Issue by rodrigost** [danielpalme/ReportGenerator#76]
Hi,

I've spent several hours to understand what is going on when I run ReportGenerator over the same source code and OpenCover files and the coverage results.

The following table shows that the same source code (commit hash) with different line and branch coverage.
![image](https://cloud.githubusercontent.com/assets/3003554/21233077/09b594c2-c2d5-11e6-82ba-fca4b6169781.png)

After checking some of the files which was impacting the coverage results, I noticed the process using an old version of the same class file and I don't get why is that happening because the folder is updated. 

It may be affected by the history folder which has around 350 files, near 340MB, and when the process is reading this folder it consumes almost 6GB memory.
![image](https://cloud.githubusercontent.com/assets/3003554/21234274/330b321a-c2d9-11e6-8abc-9d3d2c5f371b.png)

The command I am using is the following:
`.\Tools\ReportGenerator.2.5.1\tools\ReportGenerator.exe -reports:%baseDir%\CoverageReports\UnitCoverageReport_* -targetdir:%unitFolder% -reporttypes:XmlSummary;Html;HtmlSummary -historydir:%historyFolder%\Nunit\history\`

Could you help me with that issue? Why is ReportGenerator using an old version file?

Thanks,
Rodrigo

**Comment by danielpalme** [comment]
Can please explain what you mean by "using an old version file"? I don't understand that part of your question.

**Comment by rodrigost** [comment]
Sorry for that, but it means that the coverage results refer to an old source file. The actual code was improved and the tests was rearranged, but in someway when I got the variation on coverage, I could get on coverage HTML report an old version file instead of the refractories code.

**Comment by danielpalme** [comment]
I have read you issue again and I think you have three question/issues:

**1) High memory usage**
I will have a look at the code of _ReportGenerator_. I have some ideas how I could possibly reduce memory usage. The number of files in the history directory should not matter that much, since only the latest 100 are parsed by default. Your code base has ~6000 classes, that's also not that much. But you have a lot of _OpenCover_ files, that may cause the high memory consumption.

**2) Different coverage results on same code base**
In your table the _CoverableLine_ and _TotalLines_ are constant (line1/2 and line 6/7) only _CoveredLines_ and _UncoveredLines_ differ.
It seems that your source code is really the same, otherwise the _TotalLines_ would probably differ.
But: Are you sure that your unit tests produce deterministic results? Or do you have at least one test where coverage depends on your environment (date, time, network connection etc). That would explain the difference in _CoveredLines_ and _UncoveredLines_. To be 100% sure we have to compare the 73 _OpenCover_ files and see if they differ.
Are those files from both runs still available?

**3) Old version of file**
_ReportGenerator_ uses the files that are listed in your _OpenCover_ files. The full path should be visible in the reports. Are you sure a file is used that is not referenced in any of your _OpenCover_ files?

If you like, you can share your _OpenCover_ reports by email (danielpalme82@gmail.com) and give me the names of one or two classes where you think the results are wrong. Then I can have a close look.

**Comment by rodrigost** [comment]
After some digging in more detail considering your insides, I realised the OpenCover files was producing different results, it was not an ReportGenerator's issue.

**Regardings the main issue which refers to item 2 and 3**
The OpenCover results was producing non-deterministic results because it was failing without notice the execution of the testes handled on different threads (~15 threads). To solve this issue, I removed the argument -register:user on OpenCover command line and instead of that I registered manually the OpenCoverProfile.dll using regsvr32.exe.

**Item 1**
About all listed items, this one is the only one related to ReportGenerator, but I see this as minor priority item.

@danielpalme Thanks for you insides and help on my issue.
