### ISSUE TITLE
AWS S3 History Folder Support

### ISSUE THREAD

**Issue by HaroonSaid** [danielpalme/ReportGenerator#78]
We build on several build agents using bamboo, which means that the history folder is always empty.  A good feature would be have history folder point to S3 bucket.

**Comment by danielpalme** [comment]
Hi @HaroonSaid 
I made some changes to make your scenario possible. 
You can now write a custom plugin to save the files. I did not integrate S3 support directly, since other users may prefer a different storage solution like DropBox or Azure. 

First you have to upgrade to this beta version:
https://www.nuget.org/packages/ReportGenerator/2.5.3-beta1

Then you can write a custom _IHistoryStorage_ class.
I prepared a [sample project](https://github.com/danielpalme/ReportGenerator/files/755933/CustomExtensions.zip) for you, which contains a class called _AmazonS3HistoryStorage.cs_.

**Please add your bucket details and keys to this class (and maybe bucket url).**

Then compile the solution and drop the _MyCompany.CustomHistoryStorage.dll_ next to your _ReportGenerator.exe_ which you execute, to generate the reports.

Now ReportGenerator should load your plugin and use the S3 Bucket configured in the DLL.

Does it work as expected? Let me know if you have any problems.

**Comment by HaroonSaid** [comment]
Let me sure that I understand IHistoryStorage interface
IEnumerable<string> GetHistoryFilePaths() - should return a list of file name (AWS lingo Keys?)
